artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/pshemach/Wine-Quality-Prediction/raw/main/Wine-Qt.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/Wine-Qt.csv
  STATUS_FILE: artifacts/data_validation/status.txt
